# Pandas

## Pandas数据结构

### DataFrame数据结构

In [4]:
import pandas as pd

# 从文件中读取数据
players = pd.read_csv("nba.csv")  
print(type(players)) # 查看数据结构

<class 'pandas.DataFrame'>

In [5]:
print(players.shape)
print(players.index)

(458, 9)
RangeIndex(start=0, stop=458, step=1)

In [6]:
print(players.columns)

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='str')

In [7]:
print(type(players.values))

<class 'numpy.ndarray'>

In [8]:
print(players.values)

[['Avery Bradley' 'Boston Celtics' 0.0 ... 180.0 'Texas' 7730337.0]
 ['Jae Crowder' 'Boston Celtics' 99.0 ... 235.0 'Marquette' 6796117.0]
 ['John Holland' 'Boston Celtics' 30.0 ... 205.0 'Boston University' nan]
 ...
 ['Tibor Pleiss' 'Utah Jazz' 21.0 ... 256.0 nan 2900000.0]
 ['Jeff Withey' 'Utah Jazz' 24.0 ... 231.0 'Kansas' 947276.0]
 [nan nan nan ... nan nan nan]]

In [9]:
players.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [10]:
players.tail(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = players.set_index('Name') # 将球员的名字设置为索引
df.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

### Series

In [13]:
df = players.set_index('Name')
salary = df['Salary']
print(type(salary))

<class 'pandas.Series'>

In [14]:
print(salary.index)

Index(['Avery Bradley', 'Jae Crowder', 'John Holland', 'R.J. Hunter',
       'Jonas Jerebko', 'Amir Johnson', 'Jordan Mickey', 'Kelly Olynyk',
       'Terry Rozier', 'Marcus Smart',
       ...
       'Gordon Hayward', 'Rodney Hood', 'Joe Ingles', 'Chris Johnson',
       'Trey Lyles', 'Shelvin Mack', 'Raul Neto', 'Tibor Pleiss',
       'Jeff Withey', nan],
      dtype='str', name='Name', length=458)

In [15]:
salary.head()

Name
Avery Bradley    7730337.0
Jae Crowder      6796117.0
John Holland           NaN
R.J. Hunter      1148640.0
Jonas Jerebko    5000000.0
Name: Salary, dtype: float64

## 数据读取与修改

### 读取数据

In [16]:
data = pd.read_csv("nba.csv")  
players = data.set_index('Name')
players.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [17]:
players['Salary'].head() # 获取一列数据，返回Series数据类型

Name
Avery Bradley    7730337.0
Jae Crowder      6796117.0
John Holland           NaN
R.J. Hunter      1148640.0
Jonas Jerebko    5000000.0
Name: Salary, dtype: float64

In [21]:
arr2 = players['Salary'].to_numpy()
print(type(arr2))
print(arr2.shape)
print(arr2[0:5])

<class 'numpy.ndarray'>
(458,)
[7730337. 6796117.      nan 1148640. 5000000.]

In [24]:
item = players.loc['Avery Bradley', 'Salary']
print(item)

7730337.0

In [25]:
sub_df = players.loc['Avery Bradley': 'R.J. Hunter']
sub_df

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0

In [26]:
sub_df = players.loc['Avery Bradley': 'R.J. Hunter', ['Salary', 'Team', 'Number']]
sub_df

                  Salary            Team  Number
Name
Avery Bradley  7730337.0  Boston Celtics     0.0
Jae Crowder    6796117.0  Boston Celtics    99.0
John Holland         NaN  Boston Celtics    30.0
R.J. Hunter    1148640.0  Boston Celtics    28.0

In [27]:
item = players.iloc[0, 0]
print(item)

Boston Celtics

In [28]:
sub_df = players.iloc[0: 5, 0:2]
sub_df

                         Team  Number
Name
Avery Bradley  Boston Celtics     0.0
Jae Crowder    Boston Celtics    99.0
John Holland   Boston Celtics    30.0
R.J. Hunter    Boston Celtics    28.0
Jonas Jerebko  Boston Celtics     8.0

In [29]:
salary = players['Salary']
salary.head()

Name
Avery Bradley    7730337.0
Jae Crowder      6796117.0
John Holland           NaN
R.J. Hunter      1148640.0
Jonas Jerebko    5000000.0
Name: Salary, dtype: float64

In [30]:
print(salary['Avery Bradley'])

7730337.0

In [31]:
print(salary.iloc[10])

2569260.0

In [32]:
sub_df = salary.iloc[0:5]
sub_df

Name
Avery Bradley    7730337.0
Jae Crowder      6796117.0
John Holland           NaN
R.J. Hunter      1148640.0
Jonas Jerebko    5000000.0
Name: Salary, dtype: float64

### 修改数据

In [33]:
players.loc['Avery Bradley', 'Salary'] = 1000
players.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,1000.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [34]:
players['Salary'] = 2000
players.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,2000
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,2000
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,2000
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,2000
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,2000

In [35]:
players.Salary = 4000
players.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,4000
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,4000
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4000
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,4000
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,4000

### 数据排序

In [36]:
df = players.sort_values(by='Age')
df.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,4000
Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,4000
Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,4000
Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,4000
Karl-Anthony Towns,Minnesota Timberwolves,32.0,C,20.0,7-0,244.0,Kentucky,4000

In [37]:
df = players.sort_values(by='Age', ascending=False)
df.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,NaN,4000
Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,4000
Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,4000
Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4000
Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,4000

In [38]:
df = players.sort_values(by=['Age', 'Weight'], ascending=False)
df.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,4000
Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,NaN,4000
Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,4000
Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4000
Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,4000

In [39]:
df = players.sort_index()
df.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,4000
Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4000
Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,4000
Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,4000
Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,4000

## Pandas的运算

### 统计运算

In [40]:
data = pd.read_csv("nba.csv")
players = data.set_index('Name')
players.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [41]:
players.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

### 逻辑运算

In [42]:
df = players['Age'] > 25
df.head()

Name
Avery Bradley    False
Jae Crowder      False
John Holland      True
R.J. Hunter      False
Jonas Jerebko     True
Name: Age, dtype: bool

In [43]:
df = players[players['Age'] > 25] 
df.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0

### 算数运算

In [44]:
salary = players['Salary']
players['new_salary'] = salary.add(100000)
players.head()

,Team,Number,Position,Age,Height,Weight,College,Salary,new_salary
Name,,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,7830337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,6896117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,1248640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,5100000.0

In [45]:
players['new_salary'] = salary + 200000
players.head()

,Team,Number,Position,Age,Height,Weight,College,Salary,new_salary
Name,,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,7930337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,6996117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,1348640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,5200000.0

### 自定义运算

In [46]:
df = players[['Salary']].apply(lambda x: x.max() - x.min())
df

Salary    24969112.0
dtype: float64

## 缺失值处理

In [48]:
movies = pd.read_csv("imdb_top_1000.csv")

In [50]:
print(pd.isnull(movies).sum())

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64